microsoftgraph/msgraph-metadata

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

This will be the input transformation to preprocess the CSDL before handing off to typewriter. The goal is to decouple preprocessing from typewriter so we can change the preprocessing rules without having to update, test, and redeploy tyepwriter. 
Added rules from https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/src/Typewriter/MetadataPreprocessor.cs#L47

Preprocess XSLT

---

transforms/csdl/preprocess_csdl.xsl

windows10PkcsCertificateProfile
windowsPhone81SCEPCertificateProfile
androidDeviceOwnerImportedPFXCertificateProfile
Fixes https://github.com/microsoftgraph/msgraph-metadata/runs/475630025

Added contains target to new beta entities

---

transforms/csdl/preprocess_csdl.xsl

Beta is blocked until this is added.
<EntityType Name="groupPolicyUploadedDefinitionFile" BaseType="graph.groupPolicyDefinitionFile">
<Property Name="fileName" Type="Edm.String" />
<Property Name="status" Type="graph.groupPolicyUploadedDefinitionFileStatus" Nullable="false" />
<Property Name="content" Type="Edm.Binary" />
<Property Name="uploadDateTime" Type="Edm.DateTimeOffset" Nullable="false" />
<Property Name="defaultLanguageCode" Type="Edm.String" />
<Property Name="groupPolicyUploadedLanguageFiles" Type="Collection(graph.groupPolicyUploadedLanguageFile)" />
<NavigationProperty Name="groupPolicyOperations" Type="Collection(graph.groupPolicyOperation)" />
</EntityType>

Mitigate missing containment (beta gen blocked)

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Enable beta generation.
Also added namespace to transform so that we only change
definitions in the target namespace.

Removed approval/request navigation

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/readme.md

@irvinesunday I've added the change for removing conditionalAccess. I also added some docs so could you walk through the instructions to make sure they work for you.

Add docs and transform for conditionalAccess singleton

---

clean_v10_metadata/cleanMetadata.xml
clean_v10_metadata/cleanMetadataWithDescriptionsv1.0.xml

@zengin I appreciate how you added clean metadata without docs. Really helpful for review in this situation.
https://github.com/microsoftgraph/msgraph-metadata/issues/59

Remove dup actions

---

transforms/csdl/preprocess_csdl.xsl

remove unused bitlocker def from container 

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

This adds the missing ProposedNewTime functionality for .NET and Java. We have to move the ProposedNewTime parameter to the end so not to break existing clients (.NET only).
We will remove the reorder rule when we generate parameter objects with Kiota.
Related to https://github.com/microsoftgraph/msgraph-metadata/pull/64
We should see a PR with the ProposedNewTime argument added to:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Generated/requests/EventDeclineRequestBuilder.cs
TODO

Add ProposedNewTime parameter to Decline and TentativelyAccept actions 

---

transforms/csdl/readme.md

Following my recent interactions with adding and testing transforms through following the readme instructions, I can say it wasn't smooth sailing. I had to fumble a bit as some of the instructions were not very clear/direct. I thought I'd make some slight updates to the readme instructions to help the next newbie who might want to add transforms later have a smoother experience.

Update transform readme instructions

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml
transforms/csdl/readme.md

Addressing failure to compile that was first found in https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/194. 
Failure to compile has persisted through https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/197 and most recently through  https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/199. 
All PR's affected by a missing 'ContainsTarget=true' in the navigation property containg the collection of DeviceManagementComplianceActionItem's under the entity DeviceManagementScheduledActionForRule which was recently added to the beta metadata.

Adding Transform Rule for Entity Collection Causing Beta Java-SDK to Fail 

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

The schema for the transformation rule on the entity managementTemplateStepVersion was incorrect on the previous pr, thus the containsTarget line was never added on the entity. Updating the rule schema to reflect the correct schema.

managementTemplateStepVersion Rule Update

---

transforms/csdl/preprocess_csdl.xsl

Fix for build failure:
https://github.com/microsoftgraph/msgraph-beta-sdk-java/runs/5373506337?check_suite_focus=true

Add contains target to  customExtensionHandlers

---

.github/workflows/openapi-update.yml
scripts/GenerateOpenApi.ps1

depends on hidi 0.6.0 preview 1 to be released ( @MaggieKimani1 will work on that tomorrow)

- switches to hidi for CSDL to openAPI conversion

---

scripts/GenerateOpenApi.ps1

reopening of #118 which was already approved by @zengin but closed by mistake by me while merging #117

updates openapi generation process to use the error description version

---

scripts/GenerateOpenApi.ps1

- fixes a bug where the generate openapi script would commit the backup file even when successful

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_output.xml

This PR:
Resolves some of the issues raised in this GitHub issue: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/902
- Removes the containments for:
- drive/bundles
- drive/following
- drive/special
- Removes Indexability for list/activities as it only supports read.

Remove further containments and indexability

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_output.xml

Remove insertability and deletability from site resource to only apply to openApi based generation

---

transforms/csdl/preprocess_csdl.xsl

This PR closes #145 by collapsing site capability annotations into one annotations tag.

Fix duplicate annotations tag for site.

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/295

Transform to unblock java-beta release

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_output.xml

This PR closes https://github.com/microsoftgraph/msgraph-metadata/issues/131
- Adds `Referenceable` annotations for selected navigation properties. This will create `/$ref` paths fot these nav. props.

Adds referenceable annotation

---

.github/workflows/openapi-parser-validation.yml
scripts/run-openapi-validation.ps1
tools/OpenAPIParser/OpenAPIParser.csproj
tools/OpenAPIParser/Program.cs

- partial https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/782

Adds OpenAPI parsing as a gate

---

schemas/beta-Mooncake.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USSec.csdl

Schemas sync from package 1.2.6.1

Schema sync 2022-07-21 from 1.2.6.1

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Hotfix to add 'ContainsTarget=true' to 'definitions' navigation property in order to unblock java-beta sdk gen. 
https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/354

Add contains target to property

---

schemas/beta-Mooncake.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2022-08-04 from 1.2.20.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2022-10-05 from 1.2.87.1

Schema sync 2022-10-05 from 1.2.87.1

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2022-10-26 from 1.2.110.0

Schema sync 2022-10-26 from 1.2.110.0

---

graph-permissions-schema.json
specs/permissions.md

- Update $schema entry to match the $id value of the draft-07 meta-schema. (Required for validation)
- Update schema to match the updates to the spec

Update permissions schema

---

graph-permissions-schema.json
specs/permissions.md

- Fix incorrect property names
- Remove unnecessary comma

Update permissions spec

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2022-11-02 from 1.2.116.0

Schema sync 2022-11-02 from 1.2.116.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2022-11-23 from 1.2.135.0

Schema sync 2022-11-23 from 1.2.135.0

---

.github/workflows/metadata-parser-validation.yml
.github/workflows/openapi-parser-validation.yml
scripts/run-metadata-validation.ps1
scripts/run-openapi-validation.ps1

Signed-off-by: Vincent Biret <vibiret@microsoft.com>

- makes metadata validation parallels for versions

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-02-15 from 1.2.236.0

Schema sync 2023-02-15 from 1.2.236.0

---

conversion-settings/openapi.json

Adds convert settings for Kiota-based OpenAPI generation

Update convert settings for Kiota-based OpenAPI generation

---

conversion-settings/default.json
conversion-settings/graphexplorer.json
conversion-settings/powershell.json

The generated open api document should be used by power platforms and the plain devx api style setting

Task: adds default settings

---

transforms/csdl/preprocess_csdl.xsl

Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1659
Registered users should have $ref according to unblock snippet generation as well.
Reference 
- https://learn.microsoft.com/en-us/graph/api/device-delete-registeredusers?view=graph-rest-1.0&tabs=http
- https://learn.microsoft.com/en-us/graph/api/device-list-registeredusers?view=graph-rest-1.0&tabs=http

Adds Referenceable annotation for RegisteredUsers 

---

conversion-settings/powershell.json

Sets `DeclarePathParametersOnPathItem=false` for PowerShell convert settings

Set `DeclarePathParametersOnPathItem=false`

---

transforms/csdl/preprocess_csdl.xsl

Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1788

Adds expand conditions calendars and contactFolders

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-04-12 from 1.2.310.0

Schema sync 2023-04-12 from 1.2.310.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-05-04 from 1.2.332.0

Schema sync 2023-05-04 from 1.2.332.0

---

schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-05-26 from 1.3.18.2

Schema sync 2023-05-26 from 1.3.18.2

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-05-31 from 1.3.22.1

Schema sync 2023-05-31 from 1.3.22.1

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-06-02 from 1.3.26.0

Schema sync 2023-06-02 from 1.3.26.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-06-07 from 1.3.29.0

Schema sync 2023-06-07 from 1.3.29.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-06-14 from 1.3.37.0

Schema sync 2023-06-14 from 1.3.37.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-06-16 from 1.3.42.0

Schema sync 2023-06-16 from 1.3.42.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-06-21 from 1.3.45.2

Schema sync 2023-06-21 from 1.3.45.2

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-06-23 from 1.3.50.0

Schema sync 2023-06-23 from 1.3.50.0

---

transforms/csdl/preprocess_csdl.xsl

AdminUnits/members should be insertable according to the documentation. 
https://learn.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-1.0&tabs=java#http-request

Add Insertability for adminUnits/members property

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-06-30 from 1.3.57.0

Schema sync 2023-06-30 from 1.3.57.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-07-05 from 1.3.60.1

Schema sync 2023-07-05 from 1.3.60.1

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/360

Adds `ConsistencyLevel` header for `rbacApplication/transitiveRoleAssignments` navigation property

---

conversion-settings/openapi.json
conversion-settings/powershell.json
conversion-settings/powershell_v2.json

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/305

Adds `AddAlternateKeyPaths = true`

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-07-12 from 1.3.68.0

Schema sync 2023-07-12 from 1.3.68.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-Review.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-07-19 from 1.3.76.1

Schema sync 2023-07-19 from 1.3.76.1

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-Review.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-07-21 from 1.3.80.0

Schema sync 2023-07-21 from 1.3.80.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-Review.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-07-26 from 1.3.83.1

Schema sync 2023-07-26 from 1.3.83.1

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/371

Adds readability and updatability via annotations for complex property `apiConnectorConfiguration`

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-07-28 from 1.3.87.0

Schema sync 2023-07-28 from 1.3.87.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-08-11 from 1.3.102.1

Schema sync 2023-08-11 from 1.3.102.1

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-08-16 from 1.3.105.0

Schema sync 2023-08-16 from 1.3.105.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-08-18 from 1.3.109.0

Schema sync 2023-08-18 from 1.3.109.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-08-23 from 1.3.112.1

Schema sync 2023-08-23 from 1.3.112.1

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-08-30 from 1.3.120.0

Schema sync 2023-08-30 from 1.3.120.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-09-01 from 1.3.123.0

Schema sync 2023-09-01 from 1.3.123.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-09-06 from 1.3.126.0

Schema sync 2023-09-06 from 1.3.126.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/402, https://github.com/microsoftgraph/msgraph-metadata/issues/416

Adds `Insertability` for `comments` complex property and `PUT` `HttpMethod` for `identitySynchronization` nav. property

---

schemas/beta-USNat.csdl

Schema sync 2023-09-08 from 1.3.126.0

Schema sync 2023-09-08 from 1.3.126.0

---

transforms/csdl/preprocess_csdl.xsl

fix: derivedTypedFor mobileApps

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-09-13 from 1.3.129.0

Schema sync 2023-09-13 from 1.3.129.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl

Schema sync 2023-09-15 from 1.3.136.0

Schema sync 2023-09-15 from 1.3.136.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl

Schema sync 2023-09-20 from 1.3.139.0

Schema sync 2023-09-20 from 1.3.139.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-09-22 from 1.3.142.2

Schema sync 2023-09-22 from 1.3.142.2

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/428

Adds readability for complex property `serviceProvisioningErrors`

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-09-27 from 1.3.145.0

Schema sync 2023-09-27 from 1.3.145.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-09-29 from 1.3.148.0

Schema sync 2023-09-29 from 1.3.148.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-10-04 from 1.3.153.0

Schema sync 2023-10-04 from 1.3.153.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_output.xml

Revert added InsertRestrictions

External connection schema

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl

Schema sync 2023-10-06 from 1.3.156.0

Schema sync 2023-10-06 from 1.3.156.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-10-11 from 1.3.159.0

Schema sync 2023-10-11 from 1.3.159.0

---

.github/dependabot.yml
.github/workflows/metadata-parser-validation.yml
.github/workflows/openapi-parser-validation.yml

Fixes CI failing on https://github.com/microsoftgraph/msgraph-metadata/pull/458

Fixes out of date workflows and adds dependabot config for GH actions

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-10-18 from 1.3.167.0

Schema sync 2023-10-18 from 1.3.167.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-10-20 from 1.3.170.0

Schema sync 2023-10-20 from 1.3.170.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-10-25 from 1.3.173.0

Schema sync 2023-10-25 from 1.3.173.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/466

Add `AcceptableMediaTypes` to `organizationalBrandingProperties` media stream properties

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-10-27 from 1.3.177.0

Schema sync 2023-10-27 from 1.3.177.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-11-10 from 1.3.191.0

Schema sync 2023-11-10 from 1.3.191.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Referenceability for this navigation property was missed from this PR: https://github.com/microsoftgraph/msgraph-metadata/pull/473
fixes #465

Adds referenceability for `attributes` navigation property

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-11-15 from 1.3.194.0

Schema sync 2023-11-15 from 1.3.194.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Prod.csdl

Schema sync 2023-11-17 from 1.3.197.1

Schema sync 2023-11-17 from 1.3.197.1

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_output.xml

Related to PR: https://github.com/microsoftgraph/msgraph-metadata/pull/500

Sets `Required` value to `false` for `changeType` custom query option

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-12-06 from 1.3.211.0

Schema sync 2023-12-06 from 1.3.211.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_output.xml

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/528

Removes transform that made property type a collection

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2023-12-15 from 1.3.226.0

Schema sync 2023-12-15 from 1.3.226.0

---

.github/workflows/metadata-parser-validation.yml

Related to https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes

Fixes failing CI check

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Closes https://github.com/microsoftgraph/msgraph-metadata/issues/401

Fixes missing cast path for site pages

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Closes https://github.com/microsoftgraph/msgraph-metadata/issues/479

Fix missing readable and updateable annotations for signInPreferences

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-01-17 from 1.3.257.0

Schema sync 2024-01-17 from 1.3.257.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Follow up to https://github.com/microsoftgraph/msgraph-metadata/pull/299
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/553

Fixes incorrect expand restrictions for group events

---

schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-01-24 from 1.3.264.2

Schema sync 2024-01-24 from 1.3.264.2

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Prod.csdl

Schema sync 2024-01-26 from 1.3.268.0

Schema sync 2024-01-26 from 1.3.268.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-02-07 from 1.3.279.0

Schema sync 2024-02-07 from 1.3.279.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-02-09 from 1.3.283.0

Schema sync 2024-02-09 from 1.3.283.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/566

Adds `deletability` for `directory/deletedItems`

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-03-01 from 1.3.304.0

Schema sync 2024-03-01 from 1.3.304.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/572

Adds `ExplicitOperationBindings` and `RequiresExplicitBinding` annotations for `add` and `followedSites` nav. props

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-03-06 from 1.3.307.0

Schema sync 2024-03-06 from 1.3.307.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_output.xml

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/588 after conversation at https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2371#discussion_r1514408232
Also updates tests with latest changes.

Removes sites from having `add` and `remove` methods

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-03-13 from 1.3.314.0

Schema sync 2024-03-13 from 1.3.314.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Prod.csdl

Schema sync 2024-03-15 from 1.3.318.0

Schema sync 2024-03-15 from 1.3.318.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Prod.csdl

Schema sync 2024-03-22 from 1.3.325.0

Schema sync 2024-03-22 from 1.3.325.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Prod.csdl

Schema sync 2024-03-27 from 1.3.328.0

Schema sync 2024-03-27 from 1.3.328.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-04-05 from 1.3.335.0

Schema sync 2024-04-05 from 1.3.335.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-04-10 from 1.3.342.0

Schema sync 2024-04-10 from 1.3.342.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Prod.csdl

Schema sync 2024-04-24 from 1.3.346.0

Schema sync 2024-04-24 from 1.3.346.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-04-26 from 1.3.360.0

Schema sync 2024-04-26 from 1.3.360.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Prod.csdl

Schema sync 2024-05-01 from 1.3.363.0

Schema sync 2024-05-01 from 1.3.363.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl

Schema sync 2024-05-15 from 1.3.382.1

Schema sync 2024-05-15 from 1.3.382.1

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-05-17 from 1.3.389.0

Schema sync 2024-05-17 from 1.3.389.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-05-22 from 1.3.392.0

Schema sync 2024-05-22 from 1.3.392.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-05-24 from 1.3.396.0

Schema sync 2024-05-24 from 1.3.396.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl

Schema sync 2024-05-29 from 1.3.401.0

Schema sync 2024-05-29 from 1.3.401.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Changes Type attribute for properties and action/functions parameters from graph.Json to Edm.UnTyped

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Mooncake.csdl

Schema sync 2024-05-31 from 1.3.406.0

Schema sync 2024-05-31 from 1.3.406.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-07-17 from 1.3.447.0

Schema sync 2024-07-17 from 1.3.447.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Prod.csdl

Schema sync 2024-07-30 from 1.3.448.0

Schema sync 2024-07-30 from 1.3.448.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-08-13 from 1.3.452.0

Schema sync 2024-08-13 from 1.3.452.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl

Schema sync 2024-08-14 from 1.3.453.0

Schema sync 2024-08-14 from 1.3.453.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Reverts PR: https://github.com/microsoftgraph/msgraph-metadata/pull/561
Fixes issue: https://github.com/microsoftgraph/msgraph-metadata/issues/644

Reverts `IsComposable` transform

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Mooncake.csdl

Schema sync 2024-08-16 from 1.3.454.0

Schema sync 2024-08-16 from 1.3.454.0

---

schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl

Schema sync 2024-08-21 from 1.3.455.0

Schema sync 2024-08-21 from 1.3.455.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_output.xml

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/668

Adds `UpdateRestriction` annotation for `servicePrincipal/claimsPolicy`

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-08-27 from 1.3.457.0

Schema sync 2024-08-27 from 1.3.457.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-09-13 from 1.3.471.0

Schema sync 2024-09-13 from 1.3.471.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-09-17 from 1.3.473.0

Schema sync 2024-09-17 from 1.3.473.0

---

schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-09-24 from 1.3.485.0

Schema sync 2024-09-24 from 1.3.485.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-09-27 from 1.3.488.0

Schema sync 2024-09-27 from 1.3.488.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl

Schema sync 2024-10-01 from 1.3.490.0

Schema sync 2024-10-01 from 1.3.490.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/508
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2503

Adds missing referencable annotation for `managedDevice` nav properties `deviceCategory`. 

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-10-08 from 1.3.502.0

Schema sync 2024-10-08 from 1.3.502.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

Adds Readability and Updatability for requirements complex property

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-10-22 from 1.3.507.0

Schema sync 2024-10-22 from 1.3.507.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-10-25 from 1.3.509.0

Schema sync 2024-10-25 from 1.3.509.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-10-25 from 1.3.510.0

Schema sync 2024-10-25 from 1.3.510.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl

Schema sync 2024-10-29 from 1.3.510.0

Schema sync 2024-10-29 from 1.3.510.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-11-01 from 1.3.513.0

Schema sync 2024-11-01 from 1.3.513.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-11-19 from 1.3.521.0

Schema sync 2024-11-19 from 1.3.521.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2024-11-26 from 1.3.524.0

Schema sync 2024-11-26 from 1.3.524.0

---

schemas/v1.0-Fairfax.csdl

Schema sync 2024-12-17 from 1.3.530.0

Schema sync 2024-12-17 from 1.3.530.0

---

scripts/run-metadata-validation.ps1
scripts/run-openapi-validation.ps1

chore: reverts #722

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Prod.csdl

Schema sync 2024-12-24 from 1.3.531.0

Schema sync 2024-12-24 from 1.3.531.0

---

scripts/run-metadata-validation.ps1
scripts/run-openapi-validation.ps1

Reverts microsoftgraph/msgraph-metadata#739

Revert "chore: reverts #722"

---

scripts/run-metadata-validation.ps1
scripts/run-openapi-validation.ps1

restore changes reverted from https://github.com/microsoftgraph/msgraph-metadata/pull/739
To be merged pending:

chore: Unpin Hidi version

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl

Schema sync 2025-01-14 from 1.3.544.0

Schema sync 2025-01-14 from 1.3.544.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl

Schema sync 2025-01-28 from 1.3.565.0

Schema sync 2025-01-28 from 1.3.565.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-Delos.csdl
schemas/beta-GovSG.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Delos.csdl
schemas/v1.0-GovSG.csdl
schemas/v1.0-Prod.csdl

Schema sync 2025-02-04 from 1.3.579.0

Schema sync 2025-02-04 from 1.3.579.0

---

transforms/csdl/preprocess_csdl.xsl

Add missing consistency level header to support advanced queries on ``manager`` navigation property

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2025-02-11 from 1.3.585.0

Schema sync 2025-02-11 from 1.3.585.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl

Schema sync 2025-02-18 from 1.3.597.0

Schema sync 2025-02-18 from 1.3.597.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2025-02-28 from 1.3.622.0

Schema sync 2025-02-28 from 1.3.622.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl

Schema sync 2025-03-03 from 1.3.629.0

Schema sync 2025-03-03 from 1.3.629.0

---

schemas/v1.0-Bleu.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl

Schema sync 2025-03-13 from 1.3.656.0

Schema sync 2025-03-13 from 1.3.656.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-Bleu.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Bleu.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Prod.csdl

Schema sync 2025-03-31 from 1.3.691.0

Schema sync 2025-03-31 from 1.3.691.0

---

.github/workflows/metadata-parser-validation.yml
.github/workflows/openapi-parser-validation.yml

Signed-off-by: Vincent Biret <vibiret@microsoft.com>

ci: removes outdated syntax

---

schemas/annotated-v1.0-Prod.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2025-04-08 from 1.3.706.0

Schema sync 2025-04-08 from 1.3.706.0

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2025-05-02 from 1.3.741.0

Schema sync 2025-05-02 from 1.3.741.0

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2025-05-23 from 1.3.772.1

Schema sync 2025-05-23 from 1.3.772.1

---

schemas/annotated-v1.0-Prod.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2025-06-10 from 1.3.809.0

Schema sync 2025-06-10 from 1.3.809.0

---

schemas/v1.0-Mooncake.csdl

Schema sync 2025-06-17 from 1.4.4.0

Schema sync 2025-06-17 from 1.4.4.0

---

schemas/beta-Bleu.csdl
schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Bleu.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2025-07-01 from 1.4.37.0

Schema sync 2025-07-01 from 1.4.37.0

---

schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2025-07-09 from 1.4.47.0

Schema sync 2025-07-09 from 1.4.47.0

---

transforms/csdl/preprocess_csdl.xsl
transforms/csdl/preprocess_csdl_test_input.xml
transforms/csdl/preprocess_csdl_test_output.xml

This will enable generation of the SDKs to add token policies to service principal paths

fix: adds transforms to make token policies referenceable

---

schemas/beta-USNat.csdl
schemas/beta-USSec.csdl
schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl
schemas/v1.0-USNat.csdl
schemas/v1.0-USSec.csdl

Schema sync 2025-07-29 from 1.4.87.0

Schema sync 2025-07-29 from 1.4.87.0

---

schemas/v1.0-Fairfax.csdl
schemas/v1.0-Mooncake.csdl
schemas/v1.0-Prod.csdl

Schema sync 2025-08-29 from 1.4.140.0

Schema sync 2025-08-29 from 1.4.140.0
