transforms/csdl/preprocess_csdl.xsl
`edm:EntityType[@Name='teamsApp']/edm:NavigationProperty[@Name='appDefinitions']`
Sorted the containsTarget rules
Why? Because teamsAppDefinition isn't in an entityset.
<EntityType Name="teamsApp" BaseType="graph.entity">
<Property Name="externalId" Type="Edm.String" />
<Property Name="displayName" Type="Edm.String" />
<Property Name="distributionMethod" Type="graph.teamsAppDistributionMethod" />
<NavigationProperty Name="appDefinitions" Type="Collection(graph.teamsAppDefinition)" />
</EntityType>
<EntityType Name="teamsAppDefinition" BaseType="graph.entity">
<Property Name="teamsAppId" Type="Edm.String" />
<Property Name="displayName" Type="Edm.String" />
<Property Name="version" Type="Edm.String" />
</EntityType>
This is a mitigation until the fix goes in to the metadata.
=> Added containsTarget to teamsApp navigation

pipelines/validateCleanedMetadata_beta.yml, pipelines/validateCleanedMetadata_v1.0.yml, scripts/copyGeneratedFiles.ps1, scripts/runTypewriter.ps1
* Created v1.0 validation pipeline - this has run successfully.
* Created beta validation pipeline - this still needs validation, requires XSLT changes.
* Created script to download and run the latest release of typewriter.
* Created script to copy generated files.
Script example usage in script files. Expect that we will need to still
validate these changes against a scheduled build to make sure it is
configured appropriately.
new file:   pipelines/validateCleanedMetadata_beta.yml
new file:   pipelines/validateCleanedMetadata_v1.0.yml
new file:   scripts/copyGeneratedFiles.ps1
new file:   scripts/runTypewriter.ps1
=> Validate cleaned CSDL metadata with typewriter

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This fixes the issue found when [validating the beta metadata](https://o365exchange.visualstudio.com/O365%20Sandbox/_build/results?buildId=2664366&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=71c7159a-2554-5189-e11d-21665ca4648a).
To test these changes:
1. Open Visual Studio without a project.
2. Open `preprocess_csdl_test_input.xml`.
3. Select the **XML** menu from the top menu.
4. Select the **Start XSLT Without Debugging** option.
The generated file should match preprocess_csdl_test_output.xml.
The generated file should not match preprocess_csdl_test_input.xml.
Changes to be committed:
modified:   transforms/csdl/preprocess_csdl.xsl
modified:   transforms/csdl/preprocess_csdl_test_input.xml
modified:   transforms/csdl/preprocess_csdl_test_output.xml
=> Mitigate missing print service metadata

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR fixes https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/64 issue by adding [CustomQueryOptions](https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Capabilities.V1.xml#L915) capability annotation to `users`, `groups` and `bookingBusinesses` `EntitySets`. 
Custom Properties Added:
| [Users/CalendarView](https://docs.microsoft.com/en-us/graph/api/user-list-calendarview?view=graph-rest-beta&tabs=http) | [Groups/CalendarView](https://docs.microsoft.com/en-us/graph/api/group-list-calendarview?view=graph-rest-beta&tabs=http) | [BookingBusinesses/CalendarView](https://docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&tabs=http)  |
| ------------- |:-------------:| -----:|
| startDateTime | startDateTime …
=> Add Custom Query Parameters To CalendarView Nav Property

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml, transforms/csdl/readme.md, transforms/csdl/transform.ps1
The createUploadSession action was set with an additional parameter which is a breaking change for Java since Java doesn't support optional parameters (which only works when there aren't any non-nullable parameters after a nullable parameter).  I've added the original overload and have requested from the API owner that they add it back into the metadata.
Also removing an erroneous property from changeNotification, which should have been removed this week.
Added script from https://github.com/microsoftgraph/msgraph-metadata/pull/23.
@nikchett
=> Add transform script, remove property, add action

pipelines/validateCleanedMetadata_beta.yml, pipelines/validateCleanedMetadata_v1.0.yml, transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Changes include the following:
1. Remove the condition that drops namespaces
2. Update the test data to have additional namespaces
3. Update pipelines to reflect the new folder structure in `msgraph-sdk-dotnet` and `msgraph-beta-sdk-dotnet` repos.
4. Add a new rule to XSLT to address the issue that blocks generating Beta SDK. Tracking issue to fix the underlying problem in generator is opened at https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/277
[AB#5024](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5024)
=> Pipeline and XSLT updates for namespaces release

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml, transforms/csdl/transform.ps1
This PR adds consistency level header to the following AAD entity sets:
- applications
- administrativeUnits
- contacts
- devices
- groups
- servicePrincipals
- users
Closes #38
=> Consistency level header

scripts/downloadDiff.ps1
The `agent.jobstatus` environment variable has been set to read only (breaking change for us). We need to this pipeline to error when there are no changes to the metadata so that subsequent pipelines don't consider this pipeline a successful completion.
```log
##[error]Unable to process command '##vso[task.setvariable variable=agent.jobstatus;]canceled' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Overwriting readonly variable 'agent.jobstatus' is not permitted. See https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/readonly-variables.md for details.
```
=> Update downloadDiff.ps1 to fix read-only variable

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Unblocks beta generation in staging so that the Raptor pipeline can continue validating.
The team is informed to get this fixed in actual metadata.
=> adds containsTarget=true to cloudPcProvisioningPolicy.assignments

scripts/downloadDiff.ps1
TIL: AZDO does a `git init` locally, adds the remote: origin, and only fetches the head commit of master in a detached state.  So I need to fetch master.
=> Fetch master for downloaddiff

transforms/csdl/transform.ps1
- updates transform script so it supports absolute paths
This supports the dotnet core migration for typewriter.
=> - adds support for absoulte paths for transform script

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Previous XSLT rule was replacing accept, decline and tentativelyAccept actions with a parameter reordering. The reason for the rule was to keep the code backwards compatible.
Our long term solution should be to have a parameters object which can extend freely with nullable properties.
The change I propose in this PR is changing the "replace" rule with an "add" rule, which adds the backwards compatible signature. Since I remove the replace rule, the original signatures from metadata gets copied as is.
See type summary comparisons between the following two files.
[typeSummary_accept_decline_base.txt](https://github.com/microsoftgraph/msgraph-metadata/files/5823336/typeSummary_accept_decline_base.txt)
[typeSummary_accept_decline_new.txt](https://github.com/microsoftgraph/msgraph-metadata/file …
=> Fix signatures of Accept, Decline and TentativelyAccept actions

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR applies `ConsistencyLevel` header to directoryObjects EntitySet. This header will be used by AutoREST.PowerShell to generate the right request header for directoryObjects entitySet.
Closes #45.
=> Apply ConsistencyLevel header to directoryObjects EntitySet.

beta_metadata.xml, v1.0_metadata.xml
Non-fatal typewriter error in generation pipeline pushed changes to the metadata snapshots without validating with a smoke test in .NET SDK. Reverting to last known good state from Dec 8.
=> Revert metadata to last known good state

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Service team has confirmed that these need to be references. They haven't fixed the actual metadata though. Until it is fixed, removing the `ContainsTarget=true` using XSLT.
Fixes couple of Raptor tests in both V1 and Beta.
=> ContainsTarget fix for group's acceptedSenders and rejectedSenders

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
=> Revert change that caused duplicate actions

.github/workflows/metadata-parser-validation.yml, .github/workflows/openapi-update.yml, .gitmodules, scripts/run-metadata-validation.ps1, tools/MetadataParser/MetadataParser.csproj, tools/MetadataParser/Program.cs, tools/MetadataParser/README.md, transforms/csdl/preprocess_csdl.xsl
- adds OpenAPI reader as a submodule
- adds a step to MetadataParser tool to convert to OpenAPI
- adds a Github Action which will
- apply the latest XSLT rules on the latest v1 and beta metadata
- validate those transformed metadata is parsable
Fixes #62
=> OpenAPI conversion validation as a PR gate

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/readme.md, transforms/csdl/transform.ps1
You can now opt-out of removing annotations from the metadata. 
`.\transform.ps1 -removeCapaAnnotations $false`
The default behavior is to remove annotations.
Closes #69
=> Parameterize annotation removal

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Closes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/630
This PR:
- Adds `Org.OData.Capabilities.V1.NavigationRestrictions` annotations transforms for the below contained navigation properties
- microsoft.graph.driveItem/workbook --> remove navigability
- microsoft.graph.managedDevice/users --> remove indexability
- microsoft.graph.user/joinedGroups --> remove indexability
We need to check their containment using these annotations as they are incorrect and we can't delete their containment value as this might lead to unintended consequences from other dependent tools. 
Duplicate of this PR: https://github.com/microsoftgraph/msgraph-metadata/pull/76
=> Add navigation property restrictions transforms

transforms/csdl/preprocess_csdl.xsl
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/85
This PR:
- Updates the transform file to remove capability annotations from the `microsoft.graph.directoryObject` type.
=> Removes capability annotations from the DirectoryObject type

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/84
This PR: 
- Updates the transform file by:
- Adding the `workbooks` entity set if it's missing from the `EntityContainer`.
**NB**: This is a temporary workaround to add in the _workbooks_ entity set so as to unblock the metadata refreshes for DevX API.
=> Adds workbooks entity set transform

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
The transform rules in this PR are no longer useful as the ContainTarget has since been updated on these entities. We can dismiss these rules without affecting out metadata.
Also including transformation rule for entity currently causing a build failure in the latest Beta Generation: https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/200
=> Cleanup Transform Rules

.github/workflows/metadata-parser-validation.yml, scripts/run-metadata-validation.ps1, tools/MetadataParser/MetadataParser.csproj, tools/MetadataParser/Program.cs, transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml, transforms/csdl/readme.md, transforms/csdl/transform.ps1
inserts a description for the inner error type as prepration work for Kiota.
We're not describing the error itself as it's brought in the conversion process by OData conventions.
related https://github.com/microsoft/kiota/issues/411
related https://github.com/microsoft/OpenAPI.NET.OData/pull/167
More reading https://docs.microsoft.com/en-us/graph/errors
(I believe the inner error description is partly wrong, as it doesn't inherit from error according to the odata spec)
=> adds inner error description

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/111
This PR:
- Adds transforms for removing the containments of select problematic navigation properties in both the v1.0 and beta _cleanMetadataWithDescriptionsAndAnnotations_ CSDL file. These containments end up generating numerous OpenAPI paths during OData to OpenAPI conversions. This flag `<xsl:param name="remove-capability-annotations">True</xsl:param>` is checked before removing the containments (when condition is `False`). The output metadata file that the other SDKs use isn't affected.
=> Removes `ContainsTarget=true` for select problematic containment navigation properties

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml, transforms/csdl/transform.ps1
This PR closes #137 and closes #138 by reamoving deletability for `security/alerts` and `authentication/methods` as they do not support `DELETE`.
=> Remove deletability for select nav properties.

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
This PR removes insertability and deletability from site resources as described in https://docs.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-beta:
> The SharePoint API in Microsoft Graph supports the following core scenarios:
> - Access to Read-only support for site resources (no ability to create new sites)
> ...
This is done to avoid confusion as we currently generate create and delete commands for a site that are not supported by the API.
=> Remove insertability and deletability from site resources.

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR closes https://github.com/microsoftgraph/msgraph-metadata/issues/150
Related to #145 
It makes changes to the CSDL transform to add the `microsoft.graph.user/joinedGroups` annotations to cater for the v1.0 metadata. 
However, if the annotation already exists, we simply modify it by appending the subset of annotations.
This is done to prevent issues observed after work done through https://github.com/OneDrive/apidoctor/pull/116 where annotations targets should ideally be unique, and an XML document shouldn't have multiple annotation tags with the same target in the same doc.
=> Add the `microsoft.graph.user/joinedGroups` annotations otherwise modify it if exists

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml
This PR closes https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/277
It enables the generation of the `GetPstnCalls` and `GetDirectRoutingCalls` routes in the open Api document to enable the routes in the SDK generation
=> Enable GetPstnCalls and GetDirectRoutingCalls in open Api generation

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR closes #158 
Essentially, the XSLT transform had some duplicate match conditions introduced that would result in only one of the match conditions getting applied due to conflicting rules.
Ref at https://www.w3.org/TR/xslt-10/#conflict
This PR eliminates conflicting matches to allow the application of multiple changes in the event they are needed in a specific scenario.
=> Fix for referenceable annotation XSLT transform replaces some existing annotations

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR is part of https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/141
It addressed a bug in the XSLT transform that would incorrectly match the `places` EntitySet so as to add the relevant `DerivedTypeConstraint` annotation to the metadata as it failed to cater for the fact that the `EntitySet` is held within an `EntityContainer`.
The test input has been updated to validate that the fix works.
=> Fix template matching clause for `places` EntitySet

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR closes #156 by adding referenceable annotation to `internalSponsors` navigation property. See https://docs.microsoft.com/en-us/graph/api/connectedorganization-post-internalsponsors?view=graph-rest-1.0&tabs=http for more details.
=> Add referenceable annotation to `internalSponsors` nav property

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
This PR closes https://github.com/microsoftgraph/msgraph-metadata/issues/108 by making the following changes:
- Adds consistency level header to supported nav properties as documented in https://docs.microsoft.com/graph/aad-advanced-queries.
- Updates consistency level header `documentationUrl` to https://docs.microsoft.com/graph/aad-advanced-queries.
=> Add consistency level header to supported nav properties.

clean_v10_metadata/cleanMetadata.xml, clean_v10_metadata/cleanMetadataWithDescriptionsAndAnnotationsAndErrorsv1.0.xml, clean_v10_metadata/cleanMetadataWithDescriptionsAndAnnotationsv1.0.xml, clean_v10_metadata/cleanMetadataWithDescriptionsv1.0.xml, v1.0_metadata.xml
This is causing a live site issue because DevX API reads OpenAPI document directly from GitHub for snippet generation. Reverting to last known good state, i.e. last week's update. We will hit this issue again tomorrow when the generation schedule kicks in.
- Revert "Update clean metadata file with 78287 [skip ci]"
- Revert "Update clean metadata file with 78287 [skip ci]"
- Revert "Update clean metadata file with 78287 [skip ci]"
- Revert "Update clean metadata file with 78287 [skip ci]"
- Revert "Updated v1.0_metadata.xml"
- Revert "Updated beta_metadata.xml"
- Revert "Update clean metadata file with 78286 [skip ci]"
cc: @andrueastman @irvinesunday @baywet to double check if reverting causes any issues for stuff that rely on OpenAPI document. At the moment, parsing of the document seems …
=> Revert latest OpenAPI updates

.github/CODEOWNERS
all the current code owners are in north america, which reduces our resiliency to holidays
=> - adds andrew and irvine to code owners

transforms/csdl/preprocess_csdl.xsl
Related to https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/338
Reference
- https://docs.microsoft.com/en-us/graph/api/ediscovery-caseexportoperation-getdownloadurl?view=graph-rest-beta&tabs=csharp#http-request
=> Adds `DerivedTypeConstraint` annotation for caseExportOperation

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR closes #180 and closes https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/870 by adding `UpdateRestrictions` for:
- `team/schedule`. [API doc](https://learn.microsoft.com/en-us/graph/api/team-put-schedule?view=graph-rest-1.0&tabs=http)
- `entitlementManagement/accessPackageAssignmentPolicies`. [API doc](https://learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&tabs=http)
- `entitlementManagement/assignmentPolicies`. [API doc](https://learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&tabs=http)
The `UpdateRestrictions` changes the `HttpMethod` of the update operations to `PUT` as supported by the workloads.
=> Add `UpdateRestrictions` to change the update `HttpMethod` to `PUT`

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR closes #208 by making `remove directoryObject capability annotations` sub namespace agnostic.
This is needed because annotations targeting `microsoft.graph.directoryObject` were moved to `microsoft.graph.identityGovernance` sub namespace in `beta`. This move led to the bug described in #208.
In `v1.0`, the annotations targeting `microsoft.graph.directoryObject` are still under the root namespace (`microsoft.graph`).
=> Make remove directoryObject capability annotations sub namespace agnostic

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/140
- Replaces `graph.report` return type with `Edm.Stream` return type for functions with a return type of `graph.report`.
=> Replaces `graph.report` return type with `Edm.Stream` return type for matching Functions

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/216
This PR: 
- Replaces `graph.report` return type with `Edm.Stream` return type only for report functions that start with `get`.
=> Replaces `graph.report` return type with `Edm.Stream` return type only for report functions that start with `get`

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Fixes
This PR:
- Adds a FilterRestrictions annotation to the `directorySetting` entity type.
- Refactors the transform for `InsertRestrictions` and `UpdateRestrictions` for _educationSchool/administrativeUnit_ non-containment navigation property so that they are added under one target and also added even if the target already exists.
=> Add FilterRestrictions annotation transform to `directorySetting` entity type

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
related #86 #84. Adding the workbooks root node was already contreversial at the time. It's leading people to confusion and causing issues with over expansion on all OpenAPI based generation. @peombwa I understand this might be problematic for PS somehow, would you mind providing more context here? I'd support shipping a breaking change fix to remove something that never worked rather than maintaining the illusion it does work.
=> - removes ghost workbooks root path

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/248
This PR:
- Fixes the inaccuracies highlighted by the aforementioned issue above.
- Updates the output test file.
=> Fixes `ContainsTarget` inaccuracies

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/127
This PR:
- Adds/update `PUT` UpdateRestrictions for `synchronization/secrets` complex property depending on whether the `Annotations` target _microsoft.graph.synchronization/secret_ is present or not,  or whether the `Annotation` term _Org.OData.Capabilities.V1.UpdateRestrictions_ is also present or not.
- Refactors the `UpdateRestrictionsTemplate` by splitting out two other templates that can be reused within and outside the former: `UpdatableTemplate` & `UpdateMethodTemplate`
- Updates the test files appropriately.
=> Adds UpdateRestrictions annotation for the `synchronization/secrets` complex property

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR fixes #89 by applying a required `If-match` header to `planner` nav property on a `user`. The header is required when updating `plannerUser`. Requests will fail if the header is not included - https://docs.microsoft.com/en-us/graph/api/planneruser-update?view=graph-rest-beta&tabs=http.
=> Adds required `If-Match` header to planner.

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
This PR extends #259 by adding required `If-Match` header support when updating:
- group/planner
- planner/tasks
- planner/plans
- planner/buckets
- plannerTask/details
- plannerTask/assignedToTaskBoardFormat
- plannerTask/progressTaskBoardFormat
- plannerTask/bucketTaskBoardFormat
- plannerPlan/details
See https://learn.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta for additional details.
=> Extend required If-Match header support for Planner APIs

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
This PR:
- Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/236
- Removes insertability, updatability and deletability for the `applicationTemplates` entity set.
=> Add restrictions annotations for `applicationTemplates` entity set

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/262
This PR:
- Removes the property `query_string` from the ComplexProperty `searchQuery`
- Updates the integration test files.
=> Removes invalid property `query_string` from complex property `searchQuery`

transforms/csdl/preprocess_csdl.xsl
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/264
This PR:
- Uses the variable flag `open-api-generation` to control when to remove the target containments for Kiota-based CSDL
=> Remove containment only for Kiota-based CSDL

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/270
This PR:
- Removes the navigability for `driveItem/workbook` navigation property for the target CSDL file - `cleanMetadataWithDescriptionsAndAnnotations` (v1.0 and beta)
=> Adds back `NavigationRestrictions` that removes navigability for `driveItem/workbook` navigation property

.github/workflows/metadata-parser-validation.yml, .github/workflows/openapi-parser-validation.yml, conversion-settings/graphexplorer.json, conversion-settings/openapi.json, conversion-settings/powershell.json, scripts/run-metadata-validation.ps1, scripts/run-openapi-validation.ps1
Depends on the merging of [this PR](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/944) .
The new generator will need to validate the individual "platform" yaml files generated. It passes a new parameter "platformName" that tells the validation script which file to validate.
This script will change from:
> ./scripts/run-openapi-validation.ps1 -repoDirectory C:/github/msgraph-metadata -version "v1.0" 
To
> ./scripts/run-openapi-validation.ps1 -repoDirectory C:/github/msgraph-metadata -version "v1.0" -platformName "openapi"
To make sure things do not break, the `platformName` parameter is optional and set to the known available platform -> `openapi` to make sure things do not break
=> Task: Add optional parameter to support validation

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/135
This PR:
- Adds `Org.OData.Capabilities.V1.SkipSupported` annotation for the `users` entity set.
- Updates output test file.
=> Adds annotation to remove `$skip` support for the `users` entity set

transforms/csdl/preprocess_csdl.xsl
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1604
Directory objects with memberOf and TransitiveMemberOf derived constraints seem to suggest that a `group`, `device`, `orgContact`, `user` and `servicePrincipal` can be members of or transitive members of directory object types that don't have members.
=> Fixes derived constraint on `transitiveMemberOf` and `memberOf` functions

scripts/run-metadata-validation.ps1, transforms/csdl/preprocess_csdl.xsl, transforms/csdl/transform.ps1
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/282
This PR:
- Adds a new param: `csdlVersion` to be used in performing version-specific transforms. Default is set to v1.0: `v1_0`
=> Adds `csdlVersion` param

transforms/csdl/preprocess_csdl.xsl
Related to https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/526
The `deviceHealthScriptStates` property should have a `containsTarget` as true. 
The current default value causes the generated build to fail. This is because it fails to generate a collectionPage for the nav property as there is no other path that currently exists where the collection can be retrieved from (i.e. has a containsTarget for the model collection)
Reference documentation points to the collection retrieval from the nav property 
https://learn.microsoft.com/en-us/graph/api/intune-devices-devicehealthscriptpolicystate-list?view=graph-rest-beta
=> Fixes java beta generation by adding `deviceHealthScriptStates` containsTarget

transforms/csdl/preprocess_csdl.xsl
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1630
Adds insert ability  `drive/bundles` so that we we can have Post method for creating bundles in Kiota based SDKs.
Related documentation.
https://learn.microsoft.com/en-us/graph/api/drive-post-bundles?view=graph-rest-1.0&tabs=http
=> Adds insertability for drive/bundles

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1581
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1672
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1744
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1735
Mailfolders can have the `messages` property expanded.
Events/Calendarview can have the `singleValueExtendedProperties` property expanded.
Messages can have the `attachements` property expanded
=> Set expand conditions for mailFolders,messages,events and calendarView to true.

transforms/csdl/preprocess_csdl.xsl
Related to https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/538
The current default value causes the generated build to fail. This is because it fails to generate a collectionPage for the nav property as there is no other path that currently exists where the collection can be retrieved from (i.e. has a containsTarget for the model collection)
This is similar to the transform for `customExtensionHandlers` just above it.
=> Fixes java beta generation by adding `customExtensionStageSettings` containsTarget

conversion-settings/powershell_v2.json
PowerShell v2 uses different convert settings than PowerShell v1, namely:
- DeclarePathParametersOnPathItem --> false
- UseSuccessStatusCodeRange --> true
=> Add PowerShell v2 convert settings

transforms/csdl/preprocess_csdl.xsl
Follow up to https://github.com/microsoftgraph/msgraph-metadata/pull/299
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1761
Contacts are also expandable according to 
https://learn.microsoft.com/en-us/graph/api/singlevaluelegacyextendedproperty-get?view=graph-rest-1.0&tabs=http
As the annotations in the beta metadata are nested in a different namespace(`microsoft.graph.identityGovernance`), the match conditions have also been updated to capture these.
=> Set expand conditions for contacts to true

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1742
Creating team from group is done via PUT
Reference at https://learn.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=csharp
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1736
Creating externalItem is done via PUT
Reference at https://learn.microsoft.com/en-us/graph/api/externalconnectors-externalitem-create?view=graph-rest-1.0&tabs=http
=> Adds missing PUT methods for `team/group` and `externalConnection/items`

transforms/csdl/preprocess_csdl.xsl
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1791
as bookingBusinesses uses a different path in V1 metadata
Reference at https://learn.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-1.0
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1706
as `instances` also uses the custom queryparameters for `startDateTime` and `endDateTime`
Reference at https://learn.microsoft.com/en-us/graph/api/event-list-instances?view=graph-rest-1.0&tabs=http
Closes https://github.com/microsoftgraph/msgraph-sdk-go/issues/454
=> Fixes custom query parameters for bookingBusinesses.

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
XLST rules were for backwards compatibility (i.e. to prevent breaking changes). Removing it will propagate what is in the original metadata.
This will cause a breaking change in C# and Java SDKs, so it is planned to be applied for Java V3 and C# V4 major releases.
Related #21
=> Remove reordering rule for event actions

conversion-settings/powershell.json
This PR unblocks PowerShell v1 releases by setting `EnableDollarCountPath` to `false`. `\$count` is not supported in PowerShell v1 due to AutoREST.PowerShell v2 size limitation.
Also, the operationIds for `/$count` operations have an invalid hash prefix that will be fixed by https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1480.
Unblocks https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1924.
=> Set `EnableDollarCountPath` to `false` for PowerShell v1

conversion-settings/powershell_v2.json
This PR enables OData type cast paths in PowerShell v2 by setting `EnableODataTypeCast` to `true`. PowerShell can now support  OData type cast paths thanks to the recent operationId and tag names fix for OData cast paths in the conversion library - https://github.com/microsoft/OpenAPI.NET.OData/pull/338.
This PR is a partial fix for https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1228.
=> Enable OData type cast for PowerShell v2

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1814
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1680
Adds a `CustomQueryOptionsTemplate` to enable adding custom query option to various navigation properties as needed and adds `includeHiddenFolders` and  `includeHiddenMessages` query options for relevant endpoints
Ref - https://learn.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=csharp
=> Add custom query options for includeHiddenFolders and includeHiddenMessages

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR
- Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1712
- Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/258
- Closes https://github.com/microsoftgraph/msgraph-sdk-go/issues/464
Using the conversion mechanisms suggested at https://github.com/microsoft/OpenAPI.NET.OData/issues/176 the mailBoxSettings path is added to allow accessing the structural property from the path.
References
- https://learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&tabs=http (ReadRestrictions)
- https://learn.microsoft.com/en-us/graph/api/user-update-mailboxsettings?view=graph-rest-1.0&tabs=http (UpdateRestrictions)
=> Adds mailboxsettings path to openApi document

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR fixes #206 by:
- Adds `ContainsTarget="true"` attribute to `certificateBasedAuthConfiguration` navigation property.
- Removes updatability for `organization/certificateBasedAuthConfiguration` navigation property to match what's supported by API.
See supported methods at https://learn.microsoft.com/en-us/graph/api/resources/certificatebasedauthconfiguration?view=graph-rest-1.0#methods for more details.
=> Adds ContainsTarget attribute to certificateBasedAuthConfiguration navigation property

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR fixes #336 by adding addional derived types for `DeletedItems` DerivedTypeConstraint as shown in the docs -https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-beta&tabs=http#http-request.
=> Adds additional derived types for deletedItems DerivedTypeConstraint 

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/263
- Replaces single-valued with collection-valued return types for complex type `appliedConditionalAccessPolicy` for the properties:
- conditionsNotSatisfied
- conditionsSatisfied
=> Fixes response types for properties in complex type `appliedConditionalAccessPolicy`

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/328
This PR:
- Removes countability for `drives` entity set and `list/items` navigation property using `Org.OData.Capabilities.V1.CountRestrictions` annotation.
=> Removes countability using `CountRestrictions`

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/321
This PR:
- Removes `$skip` and `$top` support for `message/attachments` navigation property.
- Updates test files
=> Removes `$skip` and `$top` support for `message/attachments` navigation property

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/356
GET `/teams` is now supported in v1.0.
=> Remove `ReadRestrictions` annotation for `/teams`

.github/policies/msgraph-metadata-branch-protection.yml
Capture current policy state so that we can make versioned changes to branch protection policies. This will enable policy history, auditing, review, standardization, and templatization. We will update policy in later PR.
This branch protection policy will not take effect until https://github.com/microsoftgraph/.github/blob/main/policies/branch-protection-sdks.yml has been removed.
The yaml validation is new as we've checked in policy files without branch protection rules in them.
=> chore: capture initial branch policy settings

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Adds contains target to VirtualEventRegistration navigation properties that are missing this, fixes java-beta compile issue. 
https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/601
=> virutalEventRegistration navProperties contain target

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Closes https://github.com/microsoftgraph/msgraph-metadata/issues/329
Closes https://github.com/microsoftgraph/msgraph-sdk-go/issues/318
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1860
Closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/1152
Uses the `Org.OData.Capabilities.V1.OperationRestrictions` to add the custom query parameters to the odata function.
=> Fix event delta function parameters to include start and end dates

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Closes https://github.com/microsoftgraph/msgraph-metadata/issues/314
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1979
Uses the `Org.OData.Capabilities.V1.OperationRestrictions` to add the custom query parameters to the odata function.
=> Adds `model` custom header to getAllMessages

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Odata cast path is not being generated in openApi path due to typo in transform.
Closes https://github.com/microsoftgraph/microsoft-graph-docs/issues/21503
=> Fixes typo in `roomList` type name

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Closes https://github.com/microsoftgraph/msgraph-metadata/issues/372
Only users and service principals get to cast to `directoryRoles`
=> Fixes missing odata cast path for directory role

transforms/csdl/preprocess_csdl.xsl
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2031
ChildFolders are still mailFolders and support the custom parameter. 
https://learn.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&tabs=http#example-2-include-hidden-child-folders-under-a-specified-mail-folder
=> Adds query parameter for childfolders

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/387
=> Sets `Deletable` to `false` in `DeleteRestrictions` annotations for navigation properties of type `profilePhoto`

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/434
Removes containment for `deletedItems` navigation property. This will help stop expanding into the type cast segments of its indexer.
=> Remove containment for `deletedItems` navigation property

conversion-settings/openapi.json
Related to issue: https://github.com/microsoftgraph/msgraph-metadata/issues/434 and PR: https://github.com/microsoftgraph/msgraph-metadata/pull/442
- We can now expand derived types navigation properties.
- We are doing this for Kiota-based OpenAPI files first, and observe the change of paths then roll out for the other OpenAPI files later
=> Updates conversion setting for Kiota-based OpenAPI files

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Add `POST` method for `/external/connections/{externalConnection-id}/schema`
Remove `DELETE` method for `/external/connections/{externalConnection-id}/schema`
Fix for #438
I believe that schema cannot be deleted once it has been registered.
The `PATCH` method is only documented for [beta](https://learn.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta), but should be supported for [v1.0](https://learn.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-1.0) event though it is not documented.
=> ExternalConnection schema

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Closes #449 
Adds `Org.OData.Core.V1.ExplicitOperationBinding` and `Org.OData.Core.V1.RequiresExplicitBinding` annotations to functions bound to directory objects type to unlock generation of functions/actions on `/deletedItems` path
Depends on release of https://github.com/microsoft/OpenAPI.NET.OData/pull/430
=> Fix for operations bound to `directoryObjects/deletedItems`

.github/policies/msgraph-metadata-branch-protection.yml
Follow up to #453 
`requiresPullRequestBeforeMerging` only takes effect if `requiredApprovingReviewsCount` is 0 according to the docs at 
https://microsoft.github.io/GitOps/policies/branch-protection.html
=> Temporarily unblock generation #2

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/465
Specifically, this PR adds the required annotations to enable the 6 paths listed [here](https://github.com/microsoftgraph/msgraph-metadata/issues/465#issuecomment-1778887783).
Dependent on: https://github.com/microsoft/OpenAPI.NET.OData/issues/437
=> Adds `DerivedTypeConstraint`, `ReadRestrictions` and `Referenceable` annotations to complex and navigation properties

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/465
Enabling this complex property will allow us to expand nested complex properties to generate nested navigation properties.
This path will thus be enabled: https://learn.microsoft.com/en-us/graph/api/authenticationconditionsapplications-list-includeapplications?view=graph-rest-beta&tabs=http#http-request
_/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/conditions/applications/includeApplications/_
=> Adding `Readable` for `authenticationEventsFlow/conditions` complex property

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/480
=> Adds `changeType` custom query option to delta function for `messages`

transforms/csdl/preprocess_csdl.xsl
Date property in the innerError class should be camelCased. Otherwise it fails to deserilaize in the correct property.
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2262
=> Fixes date property casing in the innerError class

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_output.xml
Closes https://github.com/microsoftgraph/msgraph-metadata/issues/538
Fixes the missing `endDateTime` and `startDateTime` query parameters for the `calendarView` nav property on the `/users/{id}/calendarGroups/{id}/calendars/{id}/calendarView` path
=> Fixes missing calendarView query parameters. 

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes missing annotation for driveItem content after fix made in https://github.com/microsoft/OpenAPI.NET.OData/pull/470 in the conversion library.
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1621
=> Fixes missing format query parameter for `driveItem` content. 

transforms/csdl/preprocess_csdl.xsl
Follow up to https://github.com/microsoftgraph/msgraph-metadata/pull/581
`group/sites` also needs the `ExplicitOperationBindings` otherwise we witness removal of paths as seen in https://github.com/microsoftgraph/msgraph-sdk-dotnet/compare/dev...kiota/v1.0/pipelinebuild/138236
=> Follow up to #581

conversion-settings/graphexplorer.json
This PR is in relation to this PR: https://github.com/microsoft/OpenAPI.NET.OData/pull/499
And specifically this comment: https://github.com/microsoft/OpenAPI.NET.OData/pull/499#pullrequestreview-1911292349
This will enable Graph Explorer continue with the current experience of displaying generated schemas
of query options of type enums.
=> Update convert setting for GE

transforms/csdl/preprocess_csdl.xsl
Temporarily Reverts microsoftgraph/msgraph-metadata#585
The generation pipeline isn't able to push some yamls because of the size exceeding 100MB so we would need to resolve https://github.com/microsoftgraph/msgraph-metadata/issues/184 first to enable git LFS if we are to go forward. 
https://github.com/microsoftgraph/msgraph-metadata/pull/585#issuecomment-1983469978
cc @baywet @irvinesunday
=> Revert "Sets `IsComposable=true` for `workbook*` bound types"

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/593
This PR reverts the transforms added via PR: https://github.com/microsoftgraph/msgraph-metadata/pull/392 to remove deletability for `graph.user/photo` and `graph.group/photo` navigation properties.
=> Adds `deletability` support for `graph.user/photo` and `graph.group/photo`

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/427
Partially resolves: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2787
Related to: https://github.com/microsoft/OpenAPI.NET.OData/pull/543
=> Removes indexability for `invitations` entity set

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
This PR attempts to fix: https://github.com/microsoftgraph/msgraph-metadata/issues/644
Background conversation on this can be found from the same issue here: https://github.com/microsoftgraph/msgraph-metadata/issues/644#issuecomment-2233260116
=> Removes containment for `drive` navigation property for `fileStorageContainer` entity type

transforms/csdl/preprocess_csdl.xsl
Related to failing genation at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=161941&view=logs&j=ae118d5a-6432-50f6-1c0d-bcd240c6a549&t=288df45d-d1d5-59e6-efbc-8364a9b6cd55
Makes the transform for Edm.Untyped to only be for OpenApi related generation as the generation for TS typing does not support the type yet. 
Follow up to https://github.com/microsoftgraph/msgraph-metadata/pull/628
=> fix: only set Edm.Untyped for openApi related generation

.github/workflows/metadata-parser-validation.yml, scripts/run-metadata-validation.ps1
Changes made in PRs dont really upload the correct artifacts in the PR check. The simply end up uploading the same files already checked into the repository so transforms can't be validated from the artifacts.
This PR fixes the check to upload the generated file from the PR change. 
This change should still be compatible with the cleanup job done in the generation pipeline at https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/9d5561d71147cfc8008b7bed8c2712e43d93c8f5/.azure-pipelines/generation-templates/capture-metadata.yml#L123
=> Upload the correct artifacts in PR check

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/694
Temporary fix for metadata as https://github.com/microsoft/OpenAPI.NET.OData/issues/582 is being resolved
=> Remove autoReconcileProxyConflict parameter from restore action of graph.directoryObject

schemas/beta-USNat.csdl, schemas/beta-USSec.csdl, schemas/v1.0-Mooncake.csdl
Schema sync 2024-10-15 from 1.3.506.0
=> Schema sync 2024-10-15 from 1.3.506.0

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/708
To unblock weekly SDK releases, temporarily remove this parameter as we wait for resolution of https://github.com/microsoft/OpenAPI.NET.OData/issues/582
=> Remove optional parameter `forceTakeover` to the `verify` action

scripts/run-metadata-validation.ps1, scripts/run-openapi-validation.ps1
Related to https://github.com/microsoft/OpenAPI.NET.OData/issues/603 
and generation failure at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=170457&view=logs&j=c3323695-d032-5e61-7715-15770e0bec45&t=ffe81c7f-bcae-5066-faa7-4e42a6f2e612
=> fix: pin hidi version for now.

schemas/annotated-v1.0-Prod.csdl, schemas/beta-USNat.csdl, schemas/beta-USSec.csdl, schemas/v1.0-Fairfax.csdl, schemas/v1.0-Prod.csdl, schemas/v1.0-USNat.csdl, schemas/v1.0-USSec.csdl
Schema sync 2024-12-13 from 1.3.526.0
=> Schema sync 2024-12-13 from 1.3.526.0

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
=> Adds update restrictions for ``microsoft.graph.synchronizationJob/schema`` navigation property

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
=> Adds both $ref and consistency level header to manager navigation property

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml
fix: remove approleAssignments entityset navigations
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2820
After following up with the workload owners, these paths are not queriable but necessary in the metadata to unblock odata.type detection for DQ deletion responses on the v1.0 endpoint. 
This PR removes the entity set for the purposes of SDK generation.
=> fix: remove approleAssignments entityset navigations

schemas/annotated-v1.0-Prod.csdl, schemas/v1.0-Prod.csdl
Schema sync 2025-02-21 from 1.3.602.0
=> Schema sync 2025-02-21 from 1.3.602.0

schemas/beta-Bleu.csdl, schemas/beta-USNat.csdl, schemas/beta-USSec.csdl
Schema sync 2025-03-10 from 1.3.648.0
=> Schema sync 2025-03-10 from 1.3.648.0

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Related to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/3046
Adds missing derived type annotations blocking cmdlet generation cc @vidula-verma
=> fix: add missing `DerivedTypeConstraint` annotations for `protectionUnits` navigation property.

schemas/annotated-v1.0-Prod.csdl, schemas/beta-USNat.csdl, schemas/beta-USSec.csdl, schemas/v1.0-Bleu.csdl, schemas/v1.0-Fairfax.csdl, schemas/v1.0-Mooncake.csdl, schemas/v1.0-Prod.csdl, schemas/v1.0-USNat.csdl, schemas/v1.0-USSec.csdl
Schema sync 2025-04-07 from 1.3.702.0
=> Schema sync 2025-04-07 from 1.3.702.0

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Signed-off-by: Vincent Biret <vibiret@microsoft.com>
=> fix: ediscovery mandatory parameter removal

schemas/beta-USNat.csdl, schemas/beta-USSec.csdl
Schema sync 2025-04-11 from 1.3.706.0
=> Schema sync 2025-04-11 from 1.3.706.0

schemas/annotated-v1.0-Prod.csdl, schemas/beta-USNat.csdl, schemas/beta-USSec.csdl, schemas/v1.0-Bleu.csdl, schemas/v1.0-Fairfax.csdl, schemas/v1.0-Prod.csdl
Schema sync 2025-04-15 from 1.3.719.0
=> Schema sync 2025-04-15 from 1.3.719.0

schemas/annotated-v1.0-Prod.csdl, schemas/beta-Bleu.csdl, schemas/beta-Delos.csdl, schemas/beta-GovSG.csdl, schemas/beta-USNat.csdl, schemas/beta-USSec.csdl, schemas/v1.0-Bleu.csdl, schemas/v1.0-Delos.csdl, schemas/v1.0-GovSG.csdl, schemas/v1.0-Mooncake.csdl, schemas/v1.0-Prod.csdl
Schema sync 2025-05-09 from 1.3.751.0
=> Schema sync 2025-05-09 from 1.3.751.0

schemas/annotated-v1.0-Prod.csdl, schemas/beta-Bleu.csdl, schemas/beta-USNat.csdl, schemas/beta-USSec.csdl, schemas/v1.0-Fairfax.csdl, schemas/v1.0-Mooncake.csdl, schemas/v1.0-Prod.csdl
Schema sync 2025-05-16 from 1.3.767.0
=> Schema sync 2025-05-16 from 1.3.767.0

schemas/annotated-v1.0-Prod.csdl, schemas/v1.0-Fairfax.csdl, schemas/v1.0-Mooncake.csdl, schemas/v1.0-Prod.csdl
Schema sync 2025-06-03 from 1.3.800.0
=> Schema sync 2025-06-03 from 1.3.800.0

transforms/csdl/preprocess_csdl.xsl, transforms/csdl/preprocess_csdl_test_input.xml, transforms/csdl/preprocess_csdl_test_output.xml
Add navigability annotations for 'instances' and 'exceptionOccurrences' that restrict the Navigability of these navigation properties.
=> Add navigability annotations for 'instances' and 'exceptionOccurrences'

schemas/annotated-v1.0-Prod.csdl, schemas/v1.0-Prod.csdl
Schema sync 2025-06-27 from 1.4.24.0
=> Schema sync 2025-06-27 from 1.4.24.0

schemas/beta-Bleu.csdl, schemas/beta-Delos.csdl, schemas/beta-GovSG.csdl, schemas/beta-USNat.csdl, schemas/beta-USSec.csdl, schemas/v1.0-Bleu.csdl, schemas/v1.0-Delos.csdl, schemas/v1.0-Fairfax.csdl, schemas/v1.0-GovSG.csdl, schemas/v1.0-Mooncake.csdl, schemas/v1.0-Prod.csdl, schemas/v1.0-USNat.csdl, schemas/v1.0-USSec.csdl
Schema sync 2025-10-03 from 1.4.210.0
=> Schema sync 2025-10-03 from 1.4.210.0
